---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#bases:
#- ../../base

nameSuffix: -docker

namespace: node-docker

resources:
- Namespace.yaml
- ImageStream.yaml
- BuildConfig.yaml
- DeploymentConfig.yaml
- Route.yaml
- Service.yaml

commonLabels:
  app: nodejs

images:
- name: nodeimage
  newName: quay.io/lagomes/node-js-sample-project
  newTag: 'nodejs-update'

