---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: nodejs
spec:
  type: ClusterIP
  selector:
    app: nodejs  
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP