apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: nodejs
  name: node
spec:
  replicas: 3
  selector:
    app: nodejs
  strategy:
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        cpu: "200m"
        memory: "128Mi"
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: node-uat:latest
        imagePullPolicy: IfNotPresent
        name: nodejs-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            cpu: "200m"
            memory: "128Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File	
        volumeMounts:
        - name: node-data
          mountPath: /opt/app-root/src/data
      volumes:
      - name: node-data
        persistentVolumeClaim:
          claimName: pvc-node-uat
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nodejs-app
      from:
        kind: ImageStreamTag
        name: node-uat:latest
    type: ImageChange
