---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node
spec:
  accessModes:
#    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: thin-
  # storageClassName: ocs-storagecluster-cephfs  